"""
Generate beautiful prospectus for Hera in English and Korean
Matches the actual website design with purple gradient theme
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm, mm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
import os

# Hera brand colors (from the actual website)
COLORS = {
    'purple_dark': colors.HexColor('#6b21a8'),
    'purple_main': colors.HexColor('#9333ea'),
    'purple_light': colors.HexColor('#a855f7'),
    'purple_bg': colors.HexColor('#f3e8ff'),
    'white': colors.white,
    'text_dark': colors.HexColor('#1f2937'),
    'text_gray': colors.HexColor('#6b7280'),
}

def draw_gradient_rect(c, x, y, width, height, color1, color2):
    """Draw a gradient rectangle"""
    steps = 50
    for i in range(steps):
        ratio = i / steps
        r = color1.red * (1 - ratio) + color2.red * ratio
        g = color1.green * (1 - ratio) + color2.green * ratio
        b = color1.blue * (1 - ratio) + color2.blue * ratio
        c.setFillColor(colors.Color(r, g, b))
        step_height = height / steps
        c.rect(x, y + i * step_height, width, step_height, fill=True, stroke=False)

def create_prospectus_english():
    """Create English version of the prospectus"""
    filename = "Hera_Prospectus_English.pdf"
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    
    # ===== BEAUTIFUL GRADIENT HEADER =====
    draw_gradient_rect(c, 0, height - 10*cm, width, 10*cm, COLORS['purple_main'], COLORS['purple_dark'])
    
    # Decorative circles (like the website)
    c.setFillColor(colors.Color(1, 1, 1, alpha=0.1))
    c.circle(width * 0.2, height - 4*cm, 3*cm, fill=True, stroke=False)
    c.circle(width * 0.8, height - 7*cm, 4*cm, fill=True, stroke=False)
    
    # Logo/Title
    c.setFillColor(COLORS['white'])
    c.setFont("Helvetica-Bold", 52)
    c.drawCentredString(width/2, height - 4*cm, "Hera")
    
    # Emoji decoration
    c.setFont("Helvetica", 30)
    c.drawCentredString(width/2, height - 5.2*cm, "✨ 🎨 ✨")
    
    # Subtitle
    c.setFont("Helvetica", 22)
    c.drawCentredString(width/2, height - 6.5*cm, "AI-Powered Personalized Coloring Books")
    
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 7.5*cm, "For Kids Who Love to Create")
    
    # ===== MAIN CONTENT WITH MODERN CARDS =====
    y_pos = height - 12*cm
    
    # What is Hera? - Card 1
    c.setFillColor(COLORS['purple_bg'])
    c.roundRect(2*cm, y_pos - 3.5*cm, width - 4*cm, 3.5*cm, 10, fill=True, stroke=False)
    
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 18)
    c.drawString(2.5*cm, y_pos - 1*cm, "🌟 What is Hera?")
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica", 11)
    text_lines = [
        "Transform your child's imagination into beautiful personalized coloring books!",
        "Every page is unique, generated by artificial intelligence, and perfectly adapted",
        "to your child's preferences. Create magical stories in minutes."
    ]
    for i, line in enumerate(text_lines):
        c.drawString(2.5*cm, y_pos - 1.8*cm - i*0.6*cm, line)
    
    y_pos -= 4.5*cm
    
    # How it works - Step by step with icons
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 18)
    c.drawString(2.5*cm, y_pos, "⚡ How It Works")
    
    y_pos -= 1*cm
    
    steps = [
        ("1️⃣", "Choose a Theme", "Animals, Nature, Fantasy, Science, Transport, Daily Life..."),
        ("2️⃣", "Select a Style", "Ghibli, Cartoon, Minimal, Comic, Detailed, Magical..."),
        ("3️⃣", "Customize", "Number of pages (5-30), difficulty level, color palette"),
        ("4️⃣", "Get Your Book!", "Download your unique PDF or order a printed version")
    ]
    
    for emoji, title, desc in steps:
        # Colored circle for step number
        c.setFillColor(COLORS['purple_main'])
        c.circle(2.8*cm, y_pos + 0.1*cm, 0.4*cm, fill=True, stroke=False)
        
        c.setFillColor(COLORS['white'])
        c.setFont("Helvetica-Bold", 12)
        c.drawCentredString(2.8*cm, y_pos - 0.1*cm, emoji)
        
        c.setFillColor(COLORS['purple_dark'])
        c.setFont("Helvetica-Bold", 12)
        c.drawString(3.8*cm, y_pos + 0.1*cm, title)
        
        c.setFillColor(COLORS['text_dark'])
        c.setFont("Helvetica", 10)
        c.drawString(3.8*cm, y_pos - 0.4*cm, desc)
        
        y_pos -= 1.2*cm
    
    y_pos -= 0.5*cm
    
    # Features highlight box
    c.setFillColor(COLORS['purple_bg'])
    c.roundRect(2*cm, y_pos - 3*cm, width - 4*cm, 3*cm, 10, fill=True, stroke=False)
    
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2.5*cm, y_pos - 0.8*cm, "💜 Why Choose Hera?")
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica", 10)
    features = [
        "✓ Available in 6 languages (English, French, Korean, Chinese, Japanese, Spanish)",
        "✓ High-quality AI-generated illustrations",
        "✓ Instant PDF download + Optional printed book",
        "✓ Suitable for all ages and skill levels",
        "✓ Affordable: Starting at $9.99"
    ]
    for i, feat in enumerate(features):
        c.drawString(2.8*cm, y_pos - 1.6*cm - i*0.5*cm, feat)
    
    y_pos -= 4*cm
    
    # ===== TEST INSTRUCTIONS - IMPORTANT BOX =====
    c.setFillColor(colors.HexColor('#fef3c7'))
    c.setStrokeColor(colors.HexColor('#f59e0b'))
    c.setLineWidth(2)
    c.roundRect(1.5*cm, y_pos - 4*cm, width - 3*cm, 4*cm, 10, fill=True, stroke=True)
    
    c.setFillColor(colors.HexColor('#b45309'))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, y_pos - 1*cm, "🧪 TEST IT FOR FREE!")
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica", 11)
    c.drawString(2*cm, y_pos - 1.8*cm, "At checkout, use these test credit card details:")
    
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor('#b45309'))
    c.drawString(2.5*cm, y_pos - 2.5*cm, "💳 Card Number:  4242 4242 4242 4242")
    c.drawString(2.5*cm, y_pos - 3.1*cm, "📅 Expiry Date:  12/25")
    c.drawString(2.5*cm, y_pos - 3.7*cm, "🔒 CVV:  123")
    
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(COLORS['text_gray'])
    c.drawString(2*cm, y_pos - 4.3*cm, "Then enter your real email address and any name to receive your test PDF!")
    
    # ===== FOOTER WITH QR CODES =====
    footer_y = 5*cm
    
    # Decorative line
    c.setStrokeColor(COLORS['purple_main'])
    c.setLineWidth(2)
    c.line(2*cm, footer_y, width - 2*cm, footer_y)
    
    # QR Codes section title
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(width/2, footer_y - 1*cm, "📱 Scan to Connect")
    
    # Website QR Code (Left)
    try:
        qr_website = ImageReader('images/link_website.jpg')
        c.drawImage(qr_website, 4*cm, footer_y - 4.5*cm, width=3*cm, height=3*cm, preserveAspectRatio=True)
    except:
        c.setStrokeColor(COLORS['purple_main'])
        c.rect(4*cm, footer_y - 4.5*cm, 3*cm, 3*cm)
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(5.5*cm, footer_y - 5.2*cm, "🌐 Website")
    
    # Instagram QR Code (Right)
    try:
        qr_insta = ImageReader('images/insta_link.jpeg')
        c.drawImage(qr_insta, width - 7*cm, footer_y - 4.5*cm, width=3*cm, height=3*cm, preserveAspectRatio=True)
    except:
        c.setStrokeColor(COLORS['purple_main'])
        c.rect(width - 7*cm, footer_y - 4.5*cm, 3*cm, 3*cm)
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(width - 5.5*cm, footer_y - 5.2*cm, "📸 Instagram")
    
    # Contact info
    c.setFillColor(COLORS['text_gray'])
    c.setFont("Helvetica", 9)
    c.drawCentredString(width/2, 1.2*cm, "📧 hera.work.noreply@gmail.com")
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(COLORS['purple_main'])
    c.drawCentredString(width/2, 0.6*cm, "Made with 💜 by Hera Team")
    
    c.save()
    print(f"✅ English prospectus created: {filename}")

def create_prospectus_korean():
    """Create Korean version of the prospectus"""
    filename = "Hera_Prospectus_Korean.pdf"
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4
    
    # ===== BEAUTIFUL GRADIENT HEADER =====
    draw_gradient_rect(c, 0, height - 10*cm, width, 10*cm, COLORS['purple_main'], COLORS['purple_dark'])
    
    # Decorative circles
    c.setFillColor(colors.Color(1, 1, 1, alpha=0.1))
    c.circle(width * 0.2, height - 4*cm, 3*cm, fill=True, stroke=False)
    c.circle(width * 0.8, height - 7*cm, 4*cm, fill=True, stroke=False)
    
    # Logo/Title
    c.setFillColor(COLORS['white'])
    c.setFont("Helvetica-Bold", 52)
    c.drawCentredString(width/2, height - 4*cm, "Hera")
    
    # Emoji decoration
    c.setFont("Helvetica", 30)
    c.drawCentredString(width/2, height - 5.2*cm, "✨ 🎨 ✨")
    
    # Subtitle (Korean)
    c.setFont("Helvetica", 22)
    c.drawCentredString(width/2, height - 6.5*cm, "AI 기반 맞춤형 컬러링북")
    
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 7.5*cm, "창의력을 사랑하는 아이들을 위한")
    
    # ===== MAIN CONTENT =====
    y_pos = height - 12*cm
    
    # What is Hera?
    c.setFillColor(COLORS['purple_bg'])
    c.roundRect(2*cm, y_pos - 3.5*cm, width - 4*cm, 3.5*cm, 10, fill=True, stroke=False)
    
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 18)
    c.drawString(2.5*cm, y_pos - 1*cm, "🌟 Hera란 무엇인가요?")
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica", 11)
    text_lines = [
        "아이의 상상력을 아름다운 맞춤형 컬러링북으로 변환하세요!",
        "모든 페이지는 인공지능으로 생성된 고유한 디자인이며,",
        "아이의 취향에 완벽하게 맞춰집니다. 몇 분 만에 마법 같은 이야기를 만드세요."
    ]
    for i, line in enumerate(text_lines):
        c.drawString(2.5*cm, y_pos - 1.8*cm - i*0.6*cm, line)
    
    y_pos -= 4.5*cm
    
    # How it works
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 18)
    c.drawString(2.5*cm, y_pos, "⚡ 작동 방식")
    
    y_pos -= 1*cm
    
    steps = [
        ("1️⃣", "테마 선택", "동물, 자연, 판타지, 과학, 교통, 일상생활..."),
        ("2️⃣", "스타일 선택", "지브리, 만화, 미니멀, 코믹, 디테일, 마법..."),
        ("3️⃣", "맞춤 설정", "페이지 수 (5-30), 난이도, 색상 팔레트"),
        ("4️⃣", "책 받기!", "고유한 PDF 다운로드 또는 인쇄본 주문")
    ]
    
    for emoji, title, desc in steps:
        c.setFillColor(COLORS['purple_main'])
        c.circle(2.8*cm, y_pos + 0.1*cm, 0.4*cm, fill=True, stroke=False)
        
        c.setFillColor(COLORS['white'])
        c.setFont("Helvetica-Bold", 12)
        c.drawCentredString(2.8*cm, y_pos - 0.1*cm, emoji)
        
        c.setFillColor(COLORS['purple_dark'])
        c.setFont("Helvetica-Bold", 12)
        c.drawString(3.8*cm, y_pos + 0.1*cm, title)
        
        c.setFillColor(COLORS['text_dark'])
        c.setFont("Helvetica", 10)
        c.drawString(3.8*cm, y_pos - 0.4*cm, desc)
        
        y_pos -= 1.2*cm
    
    y_pos -= 0.5*cm
    
    # Features
    c.setFillColor(COLORS['purple_bg'])
    c.roundRect(2*cm, y_pos - 3*cm, width - 4*cm, 3*cm, 10, fill=True, stroke=False)
    
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2.5*cm, y_pos - 0.8*cm, "💜 왜 Hera를 선택해야 하나요?")
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica", 10)
    features = [
        "✓ 6개 언어 지원 (영어, 프랑스어, 한국어, 중국어, 일본어, 스페인어)",
        "✓ 고품질 AI 생성 일러스트",
        "✓ 즉시 PDF 다운로드 + 선택적 인쇄본",
        "✓ 모든 연령과 난이도에 적합",
        "✓ 저렴한 가격: $9.99부터"
    ]
    for i, feat in enumerate(features):
        c.drawString(2.8*cm, y_pos - 1.6*cm - i*0.5*cm, feat)
    
    y_pos -= 4*cm
    
    # ===== TEST INSTRUCTIONS =====
    c.setFillColor(colors.HexColor('#fef3c7'))
    c.setStrokeColor(colors.HexColor('#f59e0b'))
    c.setLineWidth(2)
    c.roundRect(1.5*cm, y_pos - 4*cm, width - 3*cm, 4*cm, 10, fill=True, stroke=True)
    
    c.setFillColor(colors.HexColor('#b45309'))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, y_pos - 1*cm, "🧪 무료로 테스트하세요!")
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica", 11)
    c.drawString(2*cm, y_pos - 1.8*cm, "결제 시 다음 테스트 카드 정보를 사용하세요:")
    
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor('#b45309'))
    c.drawString(2.5*cm, y_pos - 2.5*cm, "💳 카드 번호:  4242 4242 4242 4242")
    c.drawString(2.5*cm, y_pos - 3.1*cm, "📅 만료일:  12/25")
    c.drawString(2.5*cm, y_pos - 3.7*cm, "🔒 CVV:  123")
    
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(COLORS['text_gray'])
    c.drawString(2*cm, y_pos - 4.3*cm, "그런 다음 실제 이메일 주소와 이름을 입력하여 테스트 PDF를 받으세요!")
    
    # ===== FOOTER WITH QR CODES =====
    footer_y = 5*cm
    
    c.setStrokeColor(COLORS['purple_main'])
    c.setLineWidth(2)
    c.line(2*cm, footer_y, width - 2*cm, footer_y)
    
    c.setFillColor(COLORS['purple_dark'])
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(width/2, footer_y - 1*cm, "📱 스캔하여 연결하기")
    
    # QR Codes
    try:
        qr_website = ImageReader('images/link_website.jpg')
        c.drawImage(qr_website, 4*cm, footer_y - 4.5*cm, width=3*cm, height=3*cm, preserveAspectRatio=True)
    except:
        c.setStrokeColor(COLORS['purple_main'])
        c.rect(4*cm, footer_y - 4.5*cm, 3*cm, 3*cm)
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(5.5*cm, footer_y - 5.2*cm, "🌐 웹사이트")
    
    try:
        qr_insta = ImageReader('images/insta_link.jpeg')
        c.drawImage(qr_insta, width - 7*cm, footer_y - 4.5*cm, width=3*cm, height=3*cm, preserveAspectRatio=True)
    except:
        c.setStrokeColor(COLORS['purple_main'])
        c.rect(width - 7*cm, footer_y - 4.5*cm, 3*cm, 3*cm)
    
    c.setFillColor(COLORS['text_dark'])
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(width - 5.5*cm, footer_y - 5.2*cm, "📸 인스타그램")
    
    # Contact
    c.setFillColor(COLORS['text_gray'])
    c.setFont("Helvetica", 9)
    c.drawCentredString(width/2, 1.2*cm, "📧 hera.work.noreply@gmail.com")
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(COLORS['purple_main'])
    c.drawCentredString(width/2, 0.6*cm, "Made with 💜 by Hera Team")
    
    c.save()
    print(f"✅ Korean prospectus created: {filename}")

if __name__ == "__main__":
    print("🎨 Creating beautiful Hera prospectuses...\n")
    create_prospectus_english()
    create_prospectus_korean()
    print("\n✨ All prospectuses created successfully!")
    print(f"📍 Location: {os.path.abspath('.')}")
